apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "strata-rmm.serviceAccountName" . }}
  labels:
    {{- include "strata-rmm.labels" . | nindent 4 }}
  {{- with .Values.orchestrator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
